/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dinosauri;




import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;



/**
 *
 * @author ruben
 */
public class gioco extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(gioco.class.getName());
     /** 
      * Dicharo le label per le immagini
      */
    JLabel dino1;
    JLabel dino2;
    /** 
      * Dicharo le label per i punti dei gioactori
      */
    JLabel punti1;
    JLabel punti2;
    /** 
      * Dicharo la label per i commenti
      */
    JLabel commenti;
    /** 
      * Dicharo il bottone per giocare la mano
      */
    JButton bottoneGiro;
    /** 
      * Dicharo il bottone delle istruzioni
      */
    JButton istruzioni;
    /** 
      * Dicharo la text area per le carte in tavola
      */
    JTextArea carteInTavola;
    /** 
      * Dicharo le icon delle immagini dei dinosauri
      */
    ImageIcon dRosso,dVerde,dGiallo;
    /** 
     * Gestore della logica del gioco 
     */
    gestoreGioco g=new gestoreGioco();
    /** 
     * Numero di mani giocate 
     */
    private int mani=0;
    /** 
     * Punteggi dei giocatori 
     */
    int p1=0,p2=0;
     
    /**
     * Costruisce la finestra del gioco, inizializza i componenti grafici
     * e prepara i mazzi dei giocatori.
     */
    public gioco() {
        
        g.preparoMazzoTavola();
        g.distribuiscoMazzi();
        
        dRosso = new ImageIcon("immagini/dinoRosso.png");
        dVerde = new ImageIcon("immagini/dinoVerde .png");
        dGiallo = new ImageIcon("immagini/dinoGiallo.png");

        
        dino1 = new JLabel();
        dino2 = new JLabel();
        punti1 = new JLabel("Punti giocatore 1:");
        punti2 = new JLabel("Punti giocatore 2:");
        commenti=new JLabel("BENVENUTI AL GIOCO");
        punti1.setForeground(Color.WHITE);
        punti2.setForeground(Color.WHITE);
        commenti.setForeground(Color.WHITE);
        
        bottoneGiro=new JButton("GIOCA PROSSIMA CARTA");
        bottoneGiro.setBounds(380, 600, 200, 50);
        bottoneGiro.addActionListener(e -> {
            clicBottone();
        });
        istruzioni=new JButton("ISTRUZIONI");
        istruzioni.setBounds(600, 700, 150, 30);
        istruzioni.addActionListener(e -> {
            istruzioni();
        });
        
        carteInTavola=new JTextArea("CARTE IN TAVOLA");
        carteInTavola.setEditable(false);

        JPanel panel = new JPanel() {
            Image imgSfondo = new ImageIcon("immagini/sfondo.png").getImage();

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imgSfondo, 0, 0, getWidth(), getHeight(), this);
            }
        };
        panel.setLayout(null); 

        panel.add(dino1);
        panel.add(dino2);
        panel.add(punti1);
        panel.add(punti2);
        panel.add(commenti);
        panel.add(bottoneGiro);
        panel.add(istruzioni);
        panel.add(carteInTavola);
        
        panel.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                scalaComponenti();
            }
        });
        
        this.setContentPane(panel);
        this.setSize(1000, 800);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\progettiJava\\INFORMATICA\\dinosauri\\dinosauri\\sfondo.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1968, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1173, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

     
        
        
    }
    /**
     * Scala un'immagine all'interno di una jlabel in base alle dimensioni della finestra.
     * 
     * @param label JLabel da scalare
     * @param imgOriginale immagine originale
     * @param xOrig coordinata X originale
     * @param yOrig coordinata Y originale
     * @param largOrig larghezza originale
     * @param altOrig altezza originale
     * @param panelBaseW larghezza base del pannello
     * @param panelBaseH altezza base del pannello
     * @param panelAttualeW larghezza attuale del pannello
     * @param panelAttualeH altezza attuale del pannello
     */
    public void scalaLabelImmagine(JLabel label, Image imgOriginale,int xOrig, int yOrig, int largOrig, int altOrig,int panelBaseW, int panelBaseH,int panelAttualeW, int panelAttualeH) {

        double scaleX = panelAttualeW / (double) panelBaseW;
        double scaleY = panelAttualeH / (double) panelBaseH;

        int x = (int)(xOrig * scaleX);
        int y = (int)(yOrig * scaleY);
        int larg = (int)(largOrig * scaleX);
        int alt = (int)(altOrig * scaleY);

        label.setBounds(x, y, larg, alt);

        Image scaledImg = imgOriginale.getScaledInstance(larg, alt, Image.SCALE_SMOOTH);
        label.setIcon(new ImageIcon(scaledImg));
    }
    /**
     * Scala le dimensioni e le posizioni di tutti i componenti della GUI
     * in base alle dimensioni attuali del pannello.
     */
    public void scalaComponenti() {
        int panelW = getContentPane().getWidth();
        int panelH = getContentPane().getHeight();

        
        int x1 = (int)(140 * ((double)panelW / 1000));
        int y1 = (int)(300 * ((double)panelH / 800));
        int larg1 = (int)(235 * ((double)panelW / 1000));
        int alt1 = (int)(296 * ((double)panelH / 800));
        dino1.setBounds(x1, y1, larg1, alt1);
        if (dino1.getIcon() != null) {
            Image img1 = ((ImageIcon)dino1.getIcon()).getImage().getScaledInstance(larg1, alt1, Image.SCALE_SMOOTH);
            dino1.setIcon(new ImageIcon(img1));
        }

        
        int x2 = (int)(630 * ((double)panelW / 1000));
        int y2 = (int)(300 * ((double)panelH / 800));
        int larg2 = (int)(235 * ((double)panelW / 1000));
        int alt2 = (int)(296 * ((double)panelH / 800));
        dino2.setBounds(x2, y2, larg2, alt2);
        if (dino2.getIcon() != null) {
            Image img2 = ((ImageIcon)dino2.getIcon()).getImage().getScaledInstance(larg2, alt2, Image.SCALE_SMOOTH);
            dino2.setIcon(new ImageIcon(img2));
        }

        int x3 = (int)(430 * ((double)panelW / 1000));
        int y3 = (int)(700 * ((double)panelH / 800));
        int larg3 = (int)(300 * ((double)panelW / 1000));
        int alt3 = (int)(40 * ((double)panelH / 800));
        punti1.setBounds(x3, y3, larg3, alt3);
        
        int x4 = (int)(430 * ((double)panelW / 1000));
        int y4 = (int)(390 * ((double)panelH / 800));
        int larg4 = (int)(300 * ((double)panelW / 1000));
        int alt4 = (int)(40 * ((double)panelH / 800));
        punti2.setBounds(x4, y4, larg4, alt4);
        
        int x5 = (int)(430 * ((double)panelW / 1000));
        int y5 = (int)(470 * ((double)panelH / 800));
        int larg5 = (int)(300 * ((double)panelW / 1000));
        int alt5 = (int)(40 * ((double)panelH / 800));
        commenti.setBounds(x5, y5, larg5, alt5);
        
        int bx = (int)(380 * ((double)panelW / 1000));
        int by = (int)(600 * ((double)panelH / 800));
        int blarg = (int)(200 * ((double)panelW / 1000));
        int balt = (int)(50 * ((double)panelH / 800));
        bottoneGiro.setBounds(bx, by, blarg, balt);
        
        int bx1 = (int)(600 * ((double)panelW / 1000));
        int by1 = (int)(700 * ((double)panelH / 800));
        int blarg1 = (int)(150 * ((double)panelW / 1000));
        int balt1 = (int)(30 * ((double)panelH / 800));
        istruzioni.setBounds(bx1, by1, blarg1, balt1);
        
        int tx = (int)(800 * ((double)panelW / 1000));
        int ty = (int)(0 * ((double)panelH / 800));
        int tlarg = (int)(200 * ((double)panelW / 1000));
        int talt = (int)(250 * ((double)panelH / 800));
        carteInTavola.setBounds(tx, ty, tlarg, talt);
    }
    /**
     * Metodo chiamato quando si preme il pulsante "GIOCA PROSSIMA CARTA".
     * Gestisce la giocata, aggiorna le icone dei dinosauri, calcola
     * il vincitore della mano, aggiorna punteggi e commenti,
     * e disabilita il pulsante a fine partita.
     */
    public void clicBottone() {
        carta[] carte = g.giocaCarta();

        ImageIcon i1, i2;

        if (carte[0].c == colori.ROSSO) {
            i1 = dRosso;
        } else if (carte[0].c == colori.VERDE) {
            i1 = dVerde;
        } else {
            i1 = dGiallo;
        }

        if (carte[1].c == colori.ROSSO) {
            i2 = dRosso;
        } else if (carte[1].c == colori.VERDE) {
            i2 = dVerde;
        } else {
            i2 = dGiallo;
        }

        aggiornaLabel(i1, i2);
        
        int vincitore=vittoria();
        if(vincitore==1){
            vittoriaMano(g.g1);
            commenti.setText("PRENDE IL GIOCATORE 1");
            p1=g.contaPunti(g.g1);
            punti1.setText("Punti giocatore 1: "+p1);
        }
        else if(vincitore==2){
            vittoriaMano(g.g2);
            commenti.setText("PRENDE IL GIOCATORE 2");
            p2=g.contaPunti(g.g2);
            punti2.setText("Punti giocatore 2: "+p2);
        }
        else{
            commenti.setText("PAREGGIO");
            aggiornoTextArea(carte);
        }
        
        if(mani==14){
            bottoneGiro.setEnabled(false);
            commenti.setText("FINE DEL GIOCO");
            messaggio();
        }
        else{
            mani=mani+1;
        }
    }
    /**
     * Aggiorna le icone dei dinosauri dei giocatori nella GUI.
     * 
     * @param i1 icona del giocatore 1
     * @param i2 icona del giocatore 2
     */
    public void aggiornaLabel(ImageIcon i1, ImageIcon i2) {
        dino1.setIcon(i1);
        dino2.setIcon(i2);

        scalaComponenti();
    }
    /**
     * Determina il vincitore della mano corrente.
     * 
     * @return 1 se vince il giocatore 1, 2 se vince il giocatore 2, 0 se pareggio
     */
    public int vittoria(){
        return g.vincitoreMano();
    }
    /**
     * Aggiorna l'area di testo delle carte sul tavolo in caso di pareggio.
     * 
     * @param c array di carte giocate in questa mano
     */
    public void aggiornoTextArea(carta[] c){
        if (c[0].c == colori.ROSSO) {
            carteInTavola.setText(carteInTavola.getText()+"\n"+"Carta Rossa");
        } else if (c[0].c == colori.VERDE) {
            carteInTavola.setText(carteInTavola.getText()+"\n"+"Carta Verde");
        } else {
            carteInTavola.setText(carteInTavola.getText()+"\n"+"Carta Gialla");
        }

        if (c[1].c == colori.ROSSO) {
            carteInTavola.setText(carteInTavola.getText()+"\n"+"Carta Rossa");
        } else if (c[1].c == colori.VERDE) {
            carteInTavola.setText(carteInTavola.getText()+"\n"+"Carta Verde");
        } else {
            carteInTavola.setText(carteInTavola.getText()+"\n"+"Carta Gialla");
        }
    }  
    /**
     * Aggiunge le carte vinte al mazzo delle prese del giocatore
     * e pulisce il mazzo delle carte sul tavolo.
     * 
     * @param gio giocatore vincitore della mano
     */
    public void vittoriaMano(Giocatore gio){
        
        gio.aggiungiCartaPrese(g.carteTavola.carte);
        g.carteTavola.pulisci();
        carteInTavola.setText("CARTE IN TAVOLA");
            
    }
    /**
     * Mostra un messaggio finale a fine partita indicando il vincitore
     * o se c'è stato pareggio.
     */
    public void messaggio(){
        if(p1>p2){
            JOptionPane.showMessageDialog(null, "HA VINTO IL GIOCATORE 1!!! COMPLIMENTI");
        }
        else if(p1<p2){
            JOptionPane.showMessageDialog(null, "HA VINTO IL GIOCATORE 2!!! COMPLIMENTI");
        }
        else{
            JOptionPane.showMessageDialog(null, "I GIOCATORI HANNO PAREGGIATO");
        }
    }
    /**
     * Mostra una finestra con le istruzioni complete del gioco.
     */
    public void istruzioni(){
        JOptionPane.showMessageDialog(null, "Benvenuto al gioco!\n"
        + "Premi il pulsante “Gioca Carta” al centro per giocare una carta.\n\n"
        + "Carte del Giocatore 1 → a sinistra\n"
        + "Carte del Giocatore 2 → a destra\n\n"
        + "Le carte giocate vanno sul tavolo → in alto a destra,\n"
        + "specialmente in caso di pareggio.\n\n"
        + "Punteggi delle carte:\n"
        + "ROSSO → 5 punti\n"
        + "VERDE → 3 punti\n"
        + "GIALLO → 1 punto\n\n"
        + "Regole di vittoria:\n"
        + "ROSSO batte VERDE e GIALLO\n"
        + "VERDE batte GIALLO\n"
        + "Stesso colore → pareggio\n\n"
        + "Vince chi accumula più punti con le carte vinte.\n"
        + "Continua a premere “Gioca Carta” finché i mazzi non sono vuoti.");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
